/// Goal-specific motivational quotes shown on the Today header.
///
/// Sourced from design-handoff/Quotation/*.md (100 quotes per goal). Each
/// `k*QuotesEn` list is index-aligned with its Chinese counterpart so the
/// same calendar day maps to the "same" quote regardless of locale.
library;

import 'package:flutter/widgets.dart' show Locale;

import 'models.dart';

const List<String> kCutQuotes = [
  '慢一点，瘦得更稳。',
  '今天的克制，是明天的轻盈。',
  '少一点脂肪，多一点自由。',
  '不急着变瘦，只认真变好。',
  '体重会波动，方向不要改变。',
  '每一滴汗，都算数。',
  '身体的改变，藏在日复一日里。',
  '今天少一点放纵，明天多一点轻盈。',
  '不追求速成，只追求持续。',
  '你正在成为更好的自己。',
  '减脂不是惩罚，而是照顾自己。',
  '轻盈的身体，来自规律的生活。',
  '不必完美，只需坚持。',
  '每一次选择，都在塑造身体。',
  '今天的努力，时间会给答案。',
  '不和别人比较，只和昨天相比。',
  '少吃不是目的，健康才是。',
  '一步一步，身体终会回应。',
  '变瘦需要时间，放弃只需要一瞬间。',
  '让身体轻一点，让生活自由一点。',
  '不怕慢，只怕停。',
  '你的身体记得每一次坚持。',
  '减掉多余的，也留下最好的。',
  '好身材不是一天练成的。',
  '每一餐，都是一次选择。',
  '管住嘴，也别忘了善待自己。',
  '不必挨饿，也可以变瘦。',
  '合理饮食，规律运动，静待改变。',
  '今天的汗水，会成为明天的轮廓。',
  '让坚持替你完成改变。',
  '不追求极端，只追求长期。',
  '体重是数字，健康才是答案。',
  '每一次训练，都是向目标靠近。',
  '你不需要奇迹，只需要时间。',
  '今天也为自己的身体负责。',
  '少一点借口，多一点行动。',
  '生活可以享受，目标也要守住。',
  '偶尔放纵，不等于放弃。',
  '一顿饭不会改变你的身体。',
  '真正的减脂，是学会平衡。',
  '不必害怕秤上的数字。',
  '体重下降只是结果，习惯才是根本。',
  '你吃下的每一口，都值得认真对待。',
  '让规律成为你的减脂武器。',
  '不用羡慕别人，你也正在改变。',
  '今天坚持，明天轻盈。',
  '每一次运动，都在消除一点遗憾。',
  '你离目标，永远只差下一次行动。',
  '别急，身体正在回应你。',
  '好状态，比好数字更重要。',
  '不要用一天，否定很久的努力。',
  '今天没做到满分，也可以继续。',
  '减脂是一段旅程，不是一场惩罚。',
  '你可以慢，但不要停。',
  '少一点负担，多一点活力。',
  '让身体回到它喜欢的状态。',
  '每天进步一点，就已经很好。',
  '你的努力不会凭空消失。',
  '不与食物对抗，与生活和解。',
  '健康地瘦下来，才是真正的胜利。',
  '轻盈不是数字，是一种状态。',
  '训练身体，也训练耐心。',
  '今天的自律，是未来的底气。',
  '不要追赶别人，走好自己的节奏。',
  '让汗水代替焦虑。',
  '让行动代替等待。',
  '每一次坚持，都在改变身体。',
  '目标很远，但下一步很近。',
  '你不需要少吃到痛苦。',
  '吃得刚好，动得刚好。',
  '给身体足够的时间。',
  '慢慢变瘦，慢慢变强。',
  '不求最快，只求最稳。',
  '今天的你，值得被认真对待。',
  '体重下降的背后，是习惯的改变。',
  '不必害怕平台期，继续做好该做的。',
  '一天的数字，不代表全部。',
  '看趋势，不看一时。',
  '每一次选择，都在投票给未来。',
  '让健康成为减脂的底线。',
  '身体会记住你的认真。',
  '不要为了数字失去生活。',
  '好身材，也应该配得上好心情。',
  '规律，是最好的减脂方案。',
  '不求暴瘦，只求长久。',
  '每一次忍住冲动，都是一次成长。',
  '不必和昨天的自己和解，只需超越一点点。',
  '你正在慢慢靠近理想的自己。',
  '少一点焦虑，多一点耐心。',
  '身体改变之前，习惯会先改变。',
  '让每一天都成为减脂的一部分。',
  '今天认真一点，未来轻松一点。',
  '你的坚持，终会长成答案。',
  '变瘦只是开始，健康才是终点。',
  '不追求完美身材，追求更好的状态。',
  '保持节奏，改变自然发生。',
  '不要急着看到结果。',
  '好身材来自无数个普通的今天。',
  '今天也向目标靠近一点。',
  '轻盈的未来，始于今天。',
];

const List<String> kCutQuotesEn = [
  'Go slower, lose it steadier.',
  'Today\'s restraint is tomorrow\'s lightness.',
  'Less fat, more freedom.',
  'Don\'t rush to get thin — just get better, seriously.',
  'Weight will fluctuate; don\'t let your direction change.',
  'Every drop of sweat counts.',
  'Change in your body hides in day after day.',
  'A little less indulgence today, a little more lightness tomorrow.',
  'Don\'t chase quick results — chase consistency.',
  'You\'re becoming a better version of yourself.',
  'Losing fat isn\'t punishment — it\'s taking care of yourself.',
  'A lighter body comes from a regular life.',
  'No need to be perfect — just keep going.',
  'Every choice you make shapes your body.',
  'Time will answer today\'s effort.',
  'Don\'t compare to others — only to yesterday\'s you.',
  'Eating less isn\'t the goal — health is.',
  'Step by step, your body will answer.',
  'Getting lean takes time; giving up takes a second.',
  'Make your body lighter, make your life freer.',
  'Don\'t fear being slow — fear stopping.',
  'Your body remembers every time you stuck with it.',
  'Cut the excess, keep the best.',
  'A great body isn\'t built in a day.',
  'Every meal is a choice.',
  'Watch what you eat, but don\'t forget to be kind to yourself.',
  'You can get lean without starving.',
  'Eat sensibly, move regularly, and let change come.',
  'Today\'s sweat becomes tomorrow\'s shape.',
  'Let consistency do the changing for you.',
  'Don\'t chase extremes — chase the long game.',
  'Weight is a number; health is the answer.',
  'Every workout brings you closer to your goal.',
  'You don\'t need a miracle — just time.',
  'Today, take responsibility for your body again.',
  'Fewer excuses, more action.',
  'Enjoy life, but hold onto your goal.',
  'An occasional indulgence isn\'t giving up.',
  'One meal won\'t change your body.',
  'Real fat loss is learning balance.',
  'Don\'t be afraid of the number on the scale.',
  'Losing weight is just the result — habits are the root.',
  'Every bite you take deserves to be taken seriously.',
  'Let routine be your weapon for fat loss.',
  'No need to envy others — you\'re changing too.',
  'Stick with it today, feel lighter tomorrow.',
  'Every workout erases a little regret.',
  'You\'re always just one action away from your goal.',
  'Don\'t rush — your body is responding.',
  'Feeling good matters more than a good number.',
  'Don\'t let one day erase a long stretch of effort.',
  'Even an imperfect today is still worth continuing.',
  'Fat loss is a journey, not a punishment.',
  'You can go slow, just don\'t stop.',
  'Less burden, more energy.',
  'Let your body return to a state it loves.',
  'A little progress each day is already enough.',
  'Your effort doesn\'t just disappear.',
  'Don\'t fight food — make peace with life.',
  'Getting lean the healthy way is the real win.',
  'Lightness isn\'t a number — it\'s a state of being.',
  'Train your body, and train your patience.',
  'Today\'s discipline is tomorrow\'s confidence.',
  'Don\'t chase others — keep your own pace.',
  'Let sweat replace anxiety.',
  'Let action replace waiting.',
  'Every time you stick with it, your body changes.',
  'The goal is far, but the next step is close.',
  'You don\'t need to eat so little it hurts.',
  'Eat just enough, move just enough.',
  'Give your body enough time.',
  'Slowly get leaner, slowly get stronger.',
  'Not the fastest — the steadiest.',
  'Today\'s you deserves to be taken seriously.',
  'Behind every pound lost is a habit changed.',
  'Don\'t fear a plateau — keep doing what you should.',
  'One day\'s number doesn\'t tell the whole story.',
  'Watch the trend, not the moment.',
  'Every choice is a vote for your future.',
  'Let health be the bottom line of fat loss.',
  'Your body remembers your effort.',
  'Don\'t lose your life chasing a number.',
  'A great body deserves a great mood too.',
  'Routine is the best fat-loss plan.',
  'Not a crash diet — something that lasts.',
  'Every urge resisted is a moment of growth.',
  'No need to make peace with yesterday\'s you — just edge past them a little.',
  'You\'re slowly getting closer to your ideal self.',
  'Less anxiety, more patience.',
  'Before your body changes, your habits change first.',
  'Let every day be part of the fat-loss journey.',
  'A little more effort today, a little more ease tomorrow.',
  'Your persistence will eventually grow into an answer.',
  'Getting lean is just the start — health is the destination.',
  'Don\'t chase a perfect body — chase a better state.',
  'Keep the rhythm, and change happens naturally.',
  'Don\'t rush to see results.',
  'A great body comes from countless ordinary todays.',
  'Today, get a little closer to your goal again.',
  'A lighter future starts today.',
];

const List<String> kMaintainQuotes = [
  '不等状态，先开始。',
  '自律，是对未来的投资。',
  '今天做好今天的事。',
  '少一点犹豫，多一步行动。',
  '习惯，比动力更可靠。',
  '不必完美，但要继续。',
  '说到做到，是最简单的自律。',
  '没有人监督，也认真生活。',
  '坚持不是一天，而是每天。',
  '今天的选择，决定明天的状态。',
  '先完成，再追求完美。',
  '动力会消失，习惯会留下。',
  '管好今天，未来自然会来。',
  '不为一时情绪改变方向。',
  '做该做的事。',
  '目标不会自己靠近。',
  '行动，是最好的答案。',
  '少想一点，多做一点。',
  '自律不是束缚，是自由。',
  '真正的自由，来自自我管理。',
  '每一次完成，都是一次成长。',
  '你可以休息，但别放弃。',
  '失败一次，不代表失败。',
  '重新开始，永远不晚。',
  '今天没做好，明天继续。',
  '不要让一次放纵变成放弃。',
  '坚持，是反复选择正确的事情。',
  '小事做好，大事自然会发生。',
  '生活不会奖励等待。',
  '行动起来，答案自然出现。',
  '目标很远，今天很近。',
  '每天进步一点就够了。',
  '不需要每天充满动力。',
  '只需要按照计划前进。',
  '自律的尽头，是更大的自由。',
  '把想做的事情真正做完。',
  '少一点借口，多一点完成。',
  '你能控制的，是今天。',
  '不追求轰轰烈烈。',
  '做好平凡的每一天。',
  '坚持简单的事情。',
  '重复正确的事情。',
  '时间会放大你的选择。',
  '今天偷懒，明天不会替你补上。',
  '今天努力，未来会替你回答。',
  '不必羡慕别人的结果。',
  '认真走自己的路。',
  '你不需要赢过别人。',
  '只需要不输给昨天。',
  '每一天都是新的开始。',
  '给自己一个值得期待的明天。',
  '计划是方向，行动是答案。',
  '做完该做的，再享受生活。',
  '自律不是苦行，而是选择。',
  '能够控制自己，才能掌控生活。',
  '不被情绪牵着走。',
  '让习惯带你向前。',
  '先坚持，再谈结果。',
  '结果需要时间。',
  '时间需要坚持。',
  '每一次坚持都不会浪费。',
  '今天的认真，未来看得见。',
  '不要低估一天的力量。',
  '更不要低估一年的坚持。',
  '小习惯，会改变大人生。',
  '让规律成为生活的一部分。',
  '你怎样度过今天，就怎样接近未来。',
  '不怕慢，只怕没有方向。',
  '选择长期，而不是即时满足。',
  '延迟满足，是成长的能力。',
  '让行动超过欲望。',
  '让计划超过懒惰。',
  '让坚持超过情绪。',
  '今天也完成自己的承诺。',
  '不为别人努力，只为自己负责。',
  '你的生活，需要你亲自掌舵。',
  '自律，是给未来自己的礼物。',
  '今天克服一点懒惰。',
  '明天就多一点自由。',
  '每一次坚持，都在增强掌控感。',
  '不需要别人认可你的努力。',
  '做了，就是答案。',
  '你可以走得慢，但方向要对。',
  '不因暂时看不到结果而停止。',
  '时间会奖励耐心的人。',
  '坚持到最后，本身就是能力。',
  '做一个行动大于想法的人。',
  '少一点“以后”，多一点“现在”。',
  '想做，就从今天开始。',
  '今天不开始，明天还是今天。',
  '不要等最好的时候。',
  '现在就是最好的起点。',
  '自律不是压抑自己。',
  '而是选择更想要的生活。',
  '让今天配得上你的目标。',
  '把普通的日子过得认真。',
  '每一次坚持，都在塑造你。',
  '未来不是等来的。',
  '未来是今天一步一步走出来的。',
  '做好今天，成为更好的自己。',
];

const List<String> kMaintainQuotesEn = [
  'Don\'t wait to feel ready — just start.',
  'Discipline is an investment in your future.',
  'Do today\'s work today.',
  'Less hesitation, one more step of action.',
  'Habits are more reliable than motivation.',
  'You don\'t have to be perfect, just keep going.',
  'Doing what you said you would is the simplest discipline.',
  'Live seriously even when no one\'s watching.',
  'Persistence isn\'t one day — it\'s every day.',
  'Today\'s choices decide tomorrow\'s state.',
  'Finish first, perfect later.',
  'Motivation fades; habits stay.',
  'Handle today well, and the future will come on its own.',
  'Don\'t let a passing mood change your direction.',
  'Do what needs to be done.',
  'Goals don\'t come closer on their own.',
  'Action is the best answer.',
  'Think a little less, do a little more.',
  'Discipline isn\'t a cage — it\'s freedom.',
  'True freedom comes from self-management.',
  'Every finish line is a moment of growth.',
  'You can rest, just don\'t quit.',
  'One failure doesn\'t mean you\'ve failed.',
  'It\'s never too late to start over.',
  'Didn\'t do well today? Keep going tomorrow.',
  'Don\'t let one slip turn into giving up.',
  'Persistence is choosing the right thing, over and over.',
  'Do the small things well, and the big things follow.',
  'Life doesn\'t reward waiting.',
  'Take action, and the answer will appear.',
  'The goal is far, but today is close.',
  'A little progress each day is enough.',
  'You don\'t need to feel motivated every day.',
  'Just follow the plan forward.',
  'At the end of discipline lies greater freedom.',
  'Actually finish what you set out to do.',
  'Fewer excuses, more things finished.',
  'What you can control is today.',
  'Don\'t chase the dramatic.',
  'Do every ordinary day well.',
  'Stick with the simple things.',
  'Repeat the right things.',
  'Time magnifies your choices.',
  'Slack off today, and tomorrow won\'t make up for it.',
  'Work hard today, and the future will answer for you.',
  'No need to envy others\' results.',
  'Walk your own path, seriously.',
  'You don\'t need to beat anyone else.',
  'You just need to not lose to yesterday.',
  'Every day is a new beginning.',
  'Give yourself a tomorrow worth looking forward to.',
  'A plan is the direction; action is the answer.',
  'Finish what needs doing, then enjoy life.',
  'Discipline isn\'t asceticism — it\'s a choice.',
  'Only by controlling yourself can you control your life.',
  'Don\'t let your emotions lead you around.',
  'Let habit carry you forward.',
  'Persist first, talk results later.',
  'Results take time.',
  'Time takes persistence.',
  'No act of persistence is ever wasted.',
  'Today\'s effort will be visible in the future.',
  'Don\'t underestimate the power of one day.',
  'And don\'t underestimate a year of persistence.',
  'Small habits change big lives.',
  'Let routine become part of your life.',
  'However you spend today is how you approach the future.',
  'Don\'t fear being slow — fear having no direction.',
  'Choose the long game, not instant gratification.',
  'Delayed gratification is a skill of growth.',
  'Let action outpace desire.',
  'Let the plan outpace laziness.',
  'Let persistence outlast emotion.',
  'Keep your promise to yourself again today.',
  'Don\'t work hard for others — be responsible for yourself.',
  'Your life needs you at the helm.',
  'Discipline is a gift to your future self.',
  'Overcome a little laziness today.',
  'Tomorrow you\'ll have a little more freedom.',
  'Every act of persistence builds your sense of control.',
  'You don\'t need others to validate your effort.',
  'Doing it is the answer.',
  'You can walk slowly, just walk in the right direction.',
  'Don\'t stop just because results aren\'t visible yet.',
  'Time rewards the patient.',
  'Persisting to the end is itself a skill.',
  'Be someone whose actions outweigh their ideas.',
  'Less "later," more "now."',
  'If you want to do it, start today.',
  'If you don\'t start today, tomorrow is still today.',
  'Don\'t wait for the perfect moment.',
  'Right now is the best starting point.',
  'Discipline isn\'t about repressing yourself.',
  'It\'s choosing the life you want more.',
  'Make today worthy of your goal.',
  'Live your ordinary days seriously.',
  'Every act of persistence shapes you.',
  'The future doesn\'t arrive by waiting.',
  'The future is built today, one step at a time.',
  'Do today well, and become a better self.',
];

const List<String> kBulkQuotes = [
  '肌肉来自坚持，不来自幻想。',
  '每一组训练，都在塑造未来。',
  '今天举起的重量，会成为明天的力量。',
  '强壮，是一点一点练出来的。',
  '肌肉不会说谎，训练会留下痕迹。',
  '重量可以很重，目标必须清晰。',
  '一组一组练，一天一天强。',
  '训练不是证明，是积累。',
  '今天的力竭，是明天的成长。',
  '身体正在回应你的努力。',
  '增肌需要重量，也需要耐心。',
  '不急着变大，先认真训练。',
  '每一次训练，都是一次投资。',
  '肌肉需要刺激，也需要恢复。',
  '吃够、睡好、练好。',
  '强大的身体来自规律。',
  '不追求虚假的速度。',
  '时间，是增肌最好的朋友。',
  '今天的重量，是明天的起点。',
  '不怕重量大，只怕训练不认真。',
  '你的身体会记住每一次训练。',
  '每一次突破，都值得记录。',
  '进步不一定明显，但一定存在。',
  '训练质量，比盲目堆重量重要。',
  '控制动作，感受肌肉。',
  '技术稳定，力量自然增长。',
  '不与别人比较重量。',
  '举自己的重量，走自己的路。',
  '强壮不是一天发生的。',
  '每一块肌肉，都需要时间雕刻。',
  '训练是过程，成长在恢复中发生。',
  '睡眠也是训练的一部分。',
  '吃得足够，身体才有材料成长。',
  '今天认真训练，明天自然更强。',
  '每一次重复，都有意义。',
  '最后一组，往往最接近突破。',
  '不怕累，只怕没有进步。',
  '让重量见证你的成长。',
  '身体不会辜负长期主义。',
  '肌肉喜欢规律，不喜欢借口。',
  '今天比昨天多一点力量。',
  '强壮来自一次次完成。',
  '训练的尽头，是更好的自己。',
  '每一次推起，都是向上。',
  '每一次拉起，都是成长。',
  '每一次深蹲，都是力量积累。',
  '不需要天赋，只需要认真。',
  '训练可以很苦，但成长值得。',
  '不急着看到结果。',
  '先把今天的训练做好。',
  '你的极限，是下一次的起点。',
  '今天的力竭，不是失败。',
  '休息不是偷懒，是成长。',
  '让身体恢复，再继续挑战。',
  '增肌不是冲刺，是长期工程。',
  '一个月看变化，一年看蜕变。',
  '训练计划可以调整，坚持不能缺席。',
  '重量在增加，你也在成长。',
  '每一次突破都值得骄傲。',
  '认真训练的人，自带力量。',
  '先学会动作，再追求重量。',
  '稳定的训练，胜过偶尔疯狂。',
  '不要追求一次突破。',
  '让进步发生在每一次训练里。',
  '肌肉是时间留下的作品。',
  '你的身体，是你亲手塑造的。',
  '今天的汗水，会成为未来的线条。',
  '强壮是一种长期选择。',
  '训练自己，也磨炼耐心。',
  '练的是身体，沉淀的是意志。',
  '每一次坚持，都让你更接近强壮。',
  '不怕起点低，只怕不开始。',
  '先完成，再突破。',
  '今天的自己，就是最好的对手。',
  '不需要证明给别人看。',
  '让身体告诉你答案。',
  '力量不是突然出现的。',
  '每一次训练都在积累。',
  '保持训练，保持成长。',
  '让时间替你完成蜕变。',
  '训练之后，好好吃饭。',
  '训练之后，好好休息。',
  '身体需要挑战，也需要温柔。',
  '不盲目追求重量，认真对待每一次动作。',
  '好的训练，是可持续的训练。',
  '变强不是一天的事情。',
  '每一次进步，都值得庆祝。',
  '不求最快增长，只求持续成长。',
  '你正在塑造自己的力量。',
  '未来的身材，来自今天的训练。',
  '训练会结束，成长不会。',
  '今天的坚持，正在改变身体。',
  '每一组，都离目标更近。',
  '强壮不是天生的，是练出来的。',
  '让汗水成为成长的证明。',
  '认真训练，耐心等待。',
  '肌肉需要时间，也需要你。',
  '一点重量，一点进步，一点改变。',
  '坚持训练，终会看见答案。',
  '你的力量，正在一点一点长出来。',
];

const List<String> kBulkQuotesEn = [
  'Muscle comes from persistence, not fantasy.',
  'Every set shapes your future.',
  'The weight you lift today becomes tomorrow\'s strength.',
  'Strength is built little by little.',
  'Muscle doesn\'t lie — training leaves a mark.',
  'The weight can be heavy, but the goal must be clear.',
  'Set by set, day by day, stronger.',
  'Training isn\'t proof — it\'s accumulation.',
  'Today\'s failure point is tomorrow\'s growth.',
  'Your body is responding to your effort.',
  'Building muscle takes weight, and patience.',
  'Don\'t rush to bulk up — train seriously first.',
  'Every workout is an investment.',
  'Muscle needs stimulus, and recovery.',
  'Eat enough, sleep well, train well.',
  'A strong body comes from routine.',
  'Don\'t chase fake speed.',
  'Time is muscle\'s best friend.',
  'Today\'s weight is tomorrow\'s starting point.',
  'Don\'t fear heavy weight — fear a careless workout.',
  'Your body remembers every workout.',
  'Every breakthrough is worth recording.',
  'Progress isn\'t always obvious, but it\'s always there.',
  'Training quality matters more than blindly stacking weight.',
  'Control the movement, feel the muscle.',
  'Stable technique, and strength grows naturally.',
  'Don\'t compare your weight to others\'.',
  'Lift your own weight, walk your own path.',
  'Strength doesn\'t happen in a day.',
  'Every muscle needs time to be sculpted.',
  'Training is the process; growth happens during recovery.',
  'Sleep is part of training too.',
  'Eat enough, and your body has the material to grow.',
  'Train hard today, and tomorrow you\'ll naturally be stronger.',
  'Every rep has meaning.',
  'The last set is often closest to a breakthrough.',
  'Don\'t fear being tired — fear making no progress.',
  'Let the weight bear witness to your growth.',
  'Your body won\'t let down the long game.',
  'Muscle likes routine, not excuses.',
  'A little more strength today than yesterday.',
  'Strength comes from finishing, again and again.',
  'At the end of training is a better you.',
  'Every push is upward.',
  'Every pull is growth.',
  'Every squat builds strength.',
  'You don\'t need talent, just seriousness.',
  'Training can be brutal, but the growth is worth it.',
  'Don\'t rush to see results.',
  'Do today\'s training well first.',
  'Your limit today is next time\'s starting point.',
  'Today\'s failure point isn\'t failure.',
  'Rest isn\'t laziness — it\'s growth.',
  'Let your body recover, then keep challenging it.',
  'Building muscle isn\'t a sprint — it\'s a long project.',
  'See change in a month, transformation in a year.',
  'Adjust the plan if you need to — just don\'t skip persistence.',
  'As the weight goes up, so do you.',
  'Every breakthrough is worth being proud of.',
  'Those who train seriously carry their own strength.',
  'Master the movement before chasing the weight.',
  'Steady training beats the occasional frenzy.',
  'Don\'t chase a single breakthrough.',
  'Let progress happen in every workout.',
  'Muscle is a work that time leaves behind.',
  'Your body is something you sculpt with your own hands.',
  'Today\'s sweat becomes tomorrow\'s definition.',
  'Strength is a long-term choice.',
  'Train your body, and temper your patience.',
  'You train the body; what settles is willpower.',
  'Every act of persistence brings you closer to strength.',
  'Don\'t fear a low starting point — fear not starting.',
  'Finish first, break through later.',
  'Today\'s you is the best opponent.',
  'No need to prove it to anyone else.',
  'Let your body tell you the answer.',
  'Strength doesn\'t appear suddenly.',
  'Every workout adds to the total.',
  'Keep training, keep growing.',
  'Let time complete the transformation for you.',
  'After training, eat well.',
  'After training, rest well.',
  'The body needs challenge, and gentleness too.',
  'Don\'t chase weight blindly — take every rep seriously.',
  'Good training is sustainable training.',
  'Getting stronger doesn\'t happen in a day.',
  'Every bit of progress is worth celebrating.',
  'Not the fastest gains — just steady ones.',
  'You\'re sculpting your own strength.',
  'Tomorrow\'s physique comes from today\'s training.',
  'Training ends; growth doesn\'t.',
  'Today\'s persistence is changing your body.',
  'Every set brings you closer to your goal.',
  'Strength isn\'t born — it\'s built.',
  'Let sweat be proof of your growth.',
  'Train seriously, wait patiently.',
  'Muscle needs time, and it needs you.',
  'A little weight, a little progress, a little change.',
  'Keep training, and you\'ll eventually see the answer.',
  'Your strength is growing, little by little.',
];

/// The quote for [goal] on local calendar day [day], cycling through the
/// 100-quote list for that goal (a new quote roughly once a day, repeating
/// after ~100 days). Uses an absolute day count (not day-of-year) so the
/// cycle doesn't jump at a year boundary. Picks the English list when
/// [locale] is English, otherwise the original Chinese list; the same day
/// always lands on index-aligned quotes across both languages.
String goalQuoteForDay(FitnessGoal goal, DateTime day, Locale locale) {
  final useEn = locale.languageCode == 'en';
  final quotes = switch (goal) {
    FitnessGoal.cut => useEn ? kCutQuotesEn : kCutQuotes,
    FitnessGoal.maintain => useEn ? kMaintainQuotesEn : kMaintainQuotes,
    FitnessGoal.bulk => useEn ? kBulkQuotesEn : kBulkQuotes,
  };
  final epochDay = DateTime(day.year, day.month, day.day)
      .difference(DateTime(2020, 1, 1))
      .inDays;
  final index = epochDay % quotes.length;
  return quotes[index < 0 ? index + quotes.length : index];
}
